---
- name: Download and install vector packages
  become: true
  ansible.builtin.apt:
    deb: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
  notify: Start Vector service